[project]
site_name = "Queria Docs"
site_description = "日本のオープンデータカタログ Queria のドキュメント"
site_url = "https://docs.queria.io/"
repo_url = "https://github.com/flo8s/queria-cli"
repo_name = "flo8s/queria-cli"

[project.theme]
features = [
    "navigation.instant",
    "navigation.instant.progress",
    "navigation.sections",
    "navigation.expand",
    "navigation.top",
    "navigation.footer",
    "content.code.copy",
    "content.code.annotate",
    "search.suggest",
    "search.highlight",
    "toc.follow",
]

[project.theme.icon]
logo = "material/database-search"
repo = "fontawesome/brands/github"

[[project.theme.palette]]
scheme = "default"
primary = "teal"
accent = "teal"
toggle = { icon = "material/brightness-7", name = "ダークモードに切り替え" }

[[project.theme.palette]]
scheme = "slate"
primary = "teal"
accent = "teal"
toggle = { icon = "material/brightness-4", name = "ライトモードに切り替え" }

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
show_source = false
show_root_heading = true
show_root_full_path = true
show_signature_annotations = true
separate_signature = true
heading_level = 2
docstring_section_style = "spacy"

[project.markdown_extensions."pymdownx.highlight"]
anchor_linenums = true
pygments_lang_class = true

[project.markdown_extensions."pymdownx.superfences"]

[project.markdown_extensions."pymdownx.snippets"]
